"""Fixed downgrade issue

Revision ID: e45ad08cd854
Revises: 4310299806b3
Create Date: 2025-02-11 00:36:15.419238

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e45ad08cd854'
down_revision = '4310299806b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses')
    from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector

def upgrade():
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    
    # Get existing indexes on enrollments table
    existing_indexes = [index['name'] for index in inspector.get_indexes('enrollments')]

    # Only drop if index exists
    if 'unique_enrollment' in existing_indexes:
        with op.batch_alter_table('enrollments') as batch_op:
            batch_op.drop_index('unique_enrollment')

def downgrade():
    with op.batch_alter_table('enrollments') as batch_op:
        batch_op.create_index('unique_enrollment', ['student_id', 'course_id'], unique=True)


    op.drop_table('enrollments')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.drop_index('course_code')
        batch_op.drop_column('course_name')
        batch_op.drop_column('course_code')

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('enrollment_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['student_id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('enrollment_ibfk_1', 'user', ['user_id'], ['id'])
        batch_op.drop_column('student_id')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_code', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('course_name', mysql.VARCHAR(length=200), nullable=False))
        batch_op.create_index('course_code', ['course_code'], unique=True)
        batch_op.drop_column('name')

    op.create_table('enrollments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='fk_enrollments_student', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index('unique_enrollment', ['student_id'], unique=True)

    op.create_table('courses',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
